#lang sicp

(define (make-account balance password)
  (define count 0)
  (define (inc-count)
    (set! count (+ count 1))
    )
  (define (error-password x)
    "Incorrect password"
    )
  (define (call-the-cops x)
    (error "7 incorrect password attempts")
    )
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch try-password m)
    (if (eq? try-password password)
        (cond ((eq? m 'withdraw) withdraw)
              ((eq? m 'deposit) deposit)
              (else (error "Unknown request -- MAKE-ACCOUNT"
                           m)))
        (begin (inc-count)
               (if (> count 6) call-the-cops error-password))
        )
    )
  dispatch)


(define acc (make-account 100 'boneinscri))

((acc '123456 'withdraw) 40)
((acc '123456 'withdraw) 40)
((acc '123456 'withdraw) 40)
((acc '123456 'withdraw) 40)
((acc '123456 'withdraw) 40)
((acc 'boneinscri 'withdraw) 40)
((acc 'some-other-password 'deposit) 50)
((acc 'boneinscri 'deposit) 50)